### ISSUE TITLE
Different fastq files

### ISSUE THREAD

**Issue by victorsanchezarevalo** [LouisFaure/bulktools-py#1]
Hi

I am really interested in try this package, I always wanted to run DESeq in python, but I have a doubt, If I have several fastq files from different replicates of each condition. Should I run the bulk pipeline for each fastq file and then merge the adata output? Does the pipeline recognize different fastq file in the folder?

Is there any Jupiter notebook available to see an example?

Thanks

Victor

**Comment by LouisFaure** [comment]
Hi Victor,

Thank you for your interest in that package!

I apologize for the lack of documentation regarding the filename format of the fastq files. Concretely, bulktool will parse and consider the string before the first "_" as the sample. So an example of file directory would be as follow:

fastq/Sample1_S1_R1_001.fastq.gz
fastq/Sample1_S2_R1_001.fastq.gz
fastq/Sample2_S3_R1_001.fastq.gz
fastq/Sample2_S4_R1_001.fastq.gz

Hope that helps !

**Comment by victorsanchezarevalo** [comment]
Thanks! I will try.

 I have tried Deseq2py and worked great. I load the count matrix and the metadata in an Anndata object with anndata package and it worked perfectly.

Best

**Comment by LouisFaure** [comment]
I a m glad you figured it out!
