### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by victorsanchezarevalo** [LouisFaure/bulktools-py#2]
Hi Louis,

I tried to install the package (using conda as you indicated) and I had the following error:

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for bulktools

Running setup.py clean for bulktools
Failed to build bulktools
Installing collected packages: pytz, commonmark, typing-extensions, six, pyparsing, pygments, numpy, natsort, scipy, rich, python-dateutil, packaging, h5py, pandas, anndata, bulktools
  Running setup.py install for bulktools ... error
  error: subprocess-exited-with-error
 
  กม Running setup.py install for bulktools did not run successfully.
  ฉฆ exit code: 1
  จtฉค> [20 lines of output]
      running install
      /home/victor/miniconda3/envs/bulktools/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/bulktools
      copying bulktools/__init__.py -> build/lib/bulktools
      copying bulktools/pipeline.py -> build/lib/bulktools
      running egg_info
      writing bulktools.egg-info/PKG-INFO
      writing dependency_links to bulktools.egg-info/dependency_links.txt
      writing entry points to bulktools.egg-info/entry_points.txt
      writing requirements to bulktools.egg-info/requires.txt
      writing top-level names to bulktools.egg-info/top_level.txt
      reading manifest file 'bulktools.egg-info/SOURCES.txt'
      reading manifest template '[MANIFEST.in](http://manifest.in/)'
      writing manifest file 'bulktools.egg-info/SOURCES.txt'
      error: [Errno 2] No such file or directory: 'make'
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

กม Encountered error while trying to install package.
จtฉค> bulktools

Could you give me any advice, please?

Best

Victor

**Comment by LouisFaure** [comment]
I apologise for the lack of answer, I have been on a sabbatical, if you haven't found the solution, my thinking is that this is likely due to the lack of `make`, which failed silently the building of fqcounter, I would run this before:
```
conda install make
```
